# Install transcrypt (with dependencies)
# https://github.com/elasticdog/transcrypt
RUN apt-get update && \
    apt-get install -y bsdmainutils && \
    curl -L https://raw.githubusercontent.com/elasticdog/transcrypt/main/transcrypt -o /usr/local/bin/transcrypt && \
    chmod +x /usr/local/bin/transcrypt
