#!/bin/bash

## Description: Deploy project (to "production" by default)
## Usage: deploy [option...] [<selector>...]
## Example: ddev deploy staging

[[ -f 'tools/deployer' ]] || {
    phive install --copy --force-accept-unsigned 'deployphp/deployer'
}

tools/deployer deploy "${@:-production}"
